directories:
  output: dist-installer
  buildResources: build
appId: com.logicompare.app
productName: LogiCompare
copyright: Copyright © 2025 LogiCompare
files:
  - filter:
      - src/main/**/*
      - src/renderer/dist/**/*
      - package.json
extraResources:
  - from: src/main/assets
    to: assets
win:
  target: nsis
  icon: assets/icon.ico
  requestedExecutionLevel: asInvoker
  forceCodeSigning: false
  signAndEditExecutable: false
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: LogiCompare
  installerIcon: assets/icon.ico
  uninstallerIcon: assets/icon.ico
  installerHeaderIcon: assets/icon.ico
  deleteAppDataOnUninstall: false
electronVersion: 29.4.6
