/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/renderer/**/*.{html,js}',
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0040e0",
        "on-primary": "#ffffff",
        "primary-container": "#2e5bff",
        "on-primary-container": "#efefff",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b8c3ff",
        "on-primary-fixed": "#001356",
        "on-primary-fixed-variant": "#0035be",
        "secondary": "#48626e",
        "on-secondary": "#ffffff",
        "secondary-container": "#cbe7f5",
        "on-secondary-container": "#4e6874",
        "secondary-fixed": "#cbe7f5",
        "secondary-fixed-dim": "#afcbd8",
        "on-secondary-fixed": "#021f29",
        "on-secondary-fixed-variant": "#304a55",
        "tertiary": "#4a575d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#626f75",
        "on-tertiary-container": "#e4f2fa",
        "tertiary-fixed": "#d7e5ec",
        "tertiary-fixed-dim": "#bbc9d0",
        "on-tertiary-fixed": "#101d23",
        "on-tertiary-fixed-variant": "#3c494f",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f6fafe",
        "on-background": "#171c1f",
        "surface": "#f6fafe",
        "on-surface": "#171c1f",
        "surface-variant": "#dfe3e7",
        "on-surface-variant": "#434656",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f4f8",
        "surface-container": "#eaeef2",
        "surface-container-high": "#e4e9ed",
        "surface-container-highest": "#dfe3e7",
        "surface-dim": "#d6dade",
        "surface-bright": "#f6fafe",
        "surface-tint": "#124af0",
        "outline": "#747688",
        "outline-variant": "#c4c5d9",
        "inverse-surface": "#2c3134",
        "inverse-on-surface": "#edf1f5",
        "inverse-primary": "#b8c3ff",
      },
      fontFamily: {
        "headline": ["Roboto", "sans-serif"],
        "body": ["Roboto", "sans-serif"],
        "label": ["Roboto", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "full": "9999px",
      },
      boxShadow: {
        "ambient": "0px 4px 20px rgba(23, 28, 31, 0.06)",
        "ambient-lg": "0px 8px 32px rgba(23, 28, 31, 0.10)",
      },
    },
  },
  plugins: [],
}
